#!/bin/sh
#
# Install from mmm-mode into PG by copying relevant files
# Run from inside mmm-mode distrib
#
# mmm-install,v 11.0 2010/10/10 22:56:59 da Exp
#
NOTICES="AUTHORS COPYING FAQ INSTALL NEWS README TODO"
DOCS="mmm.texinfo version.texi"
ELISP=*.el
MMMDIR=~/PG/mmm

rm -f $MMMDIR/*
cp -p $NOTICES $DOCS $ELISP $MMMDIR



